"""init

Revision ID: 89350061d247
Revises: 
Create Date: 2019-06-22 18:12:00.211086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89350061d247'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('karma', sa.Integer(), nullable=True),
    sa.Column('user_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_class_id'], ['user_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('asker', sa.Integer(), nullable=True),
    sa.Column('date_asked', sa.DateTime(), nullable=False),
    sa.Column('date_resolved', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asker'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_classes')
    # ### end Alembic commands ###
